version: '3.0'
services:

  # Container of the backend
  back:
    build: ./back
    container_name: back
    command: sh -c "yarn && yarn start"
    environment:
      - API_KEY_TWITTER=${API_KEY_TWITTER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    ports:
      - 3001:3001
    volumes:
        - ./logs.json:/usr/src/app/logs.json
    depends_on:
       - filter-processor

  # Container of the frontend client
  front-client:
    container_name: front-client
    build: ./front-client
    command: sh -c "yarn && yarn start"
    restart: always
    ports:
      - 80:3000
    depends_on:
      - back

  # Container of the frontend admin
  front-admin:
    container_name: front-admin
    build: ./front-admin
    command: sh -c "yarn && yarn start"
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - back

  # Container of the filters
  filter-processor:
    container_name: filter-processor
    build: ./filter-processor
    command: flask --app src/app.py run --host 0.0.0.0 --port 5000
    restart: always
    ports:
      - 5000:5000
