version: '3.0'
services:

  # Container of the backend
  back:
    image: node:18-alpine
    container_name: back
    volumes:
      - ./back:/app
    working_dir: /app
    command: yarn start
    ports:
      - 3001:3001
    depends_on:
      - filter-processor

  # Container of the frontend client
  front-client:
    image: node:18-alpine
    container_name: front-client
    restart: always
    ports:
      - 80:3000
    depends_on:
      - back
    volumes:
      - ./front-client:/app
    command: yarn start
    working_dir: /app

  # Container of the frontend admin
  front-admin:
    image: node:18-alpine
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - back
    volumes:
      - ./front-admin:/app
    command: yarn start
    working_dir: /app

  # Container of the filters
  filter-processor:
    image: python:3.8-alpine
    container_name: filter-processor
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./filter-processor:/app
    working_dir: /app
    command: >
      sh -c "pip install -r requirements.txt &&
             flask --app src/app.py run --host 0.0.0.0 --port 5000"
