version: '3.0'
services:

  # Container of the backend
  back:
    build: # "context" and "dockerfile" fields have to be under "build"
      context: back
      dockerfile: Dockerfile
    container_name: back_wallcaster
    restart: always
    ports:
      - 3001:3001

  # Container of the frontend
  front:
    build: # "context" and "dockerfile" fields have to be under "build"
      context: front-client
      dockerfile: Dockerfile
    container_name: front-client_wallcaster
    restart: always
    ports:
      - 80:3000
    depends_on:
      - back
  
  # Container of the filters
  filter-processor:
    build:
      context: filter-processor
      dockerfile: Dockerfile
    container_name: filter-processor_wallcaster
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - back
