version: '3.0'
services:
  # Container of the backend
  back:
    image: node:18-alpine
    container_name: back
    volumes:
      - ./back:/app
    working_dir: /app
    command: sh -c "yarn && yarn start"
    
    ports:
      - 3001:3001
    # depends_on:
    #   - filter-processor

  # Container of the frontend client
  front-client:
    image: node:18-alpine
    container_name: front-client
    restart: always
    ports:
      - 80:3000
    depends_on:
      - back
    volumes:
      - ./front-client:/app
    command: sh -c "yarn && yarn start"
    working_dir: /app

  # Container of the frontend admin
  front-admin:
    image: node:18-alpine
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - back
    volumes:
      - ./front-admin:/app
    command: sh -c "yarn && yarn start"
    working_dir: /app

  # Container of the filters
  filter-processor:
    build: ./filter-processor
    container_name: filter-processor
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./filter-processor:/app
      - ./filter-processor/src/nltk_data/:/root/nltk_data/
    working_dir: /app

  # Container of the filters fr-en
  filter-processor-fr-en:
    build: ./filter-processor-fr-en
    container_name: filter-processor-fr-en
    restart: always
    ports:
      - 5001:5000
    volumes:
      - ./filter-processor-fr-en:/app
      - ./filter-processor-fr-en/src/nltk_data/:/root/nltk_data/
    working_dir: /app
